### ISSUE TITLE
Cycles not showing textures

### ISSUE THREAD

**Issue by Waxiczek** [amorgun/blender_dow#1]
When using EEVEE, everything works fine. But when changed to Cycles, textures are not shown.

![Cycles](https://github.com/user-attachments/assets/24e4fc88-25ae-43a6-96df-0db8e870ab71)
![EEVEE](https://github.com/user-attachments/assets/1296d2ec-1bf9-4888-a4a5-2825ca2cd5a1)

**Comment by amorgun** [comment]
Thanks for the report. I've committed the fix and it will be a part of release 0.13.
