### ISSUE TITLE
Blender after export, unbinds the mesh from the new bones in the model!

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#10]
Hello! When creating a new bone or a copy of it, and then fixing it on the mesh, it all works in blender and you can safely customize animations, but after exporting the created bone is detached from the mesh and does not move the mesh..... if you import the same model, the bones are there, but the mesh is not attached... 

The first photo, before exporting.
![Скриншот 27-11-2024 015254](https://github.com/user-attachments/assets/07ecabaa-0366-4d42-bcd3-df8181fc345d)

Second photo, after exporting and opening again this model in blender.
![Скриншот 27-11-2024 015404](https://github.com/user-attachments/assets/11b60931-d49a-4e15-b32c-d7f7a1b4e798)

I attached the mesh and bone with ctr+p then selected “Bone”. And everything worked and I was able to make animations of firing, while rotating horizontally machine gun tank.

**Comment by amorgun** [comment]
> I attached the mesh and bone with ctr+p then selected “Bone”. And everything worked and I was able to make animations of firing, while rotating horizontally machine gun tank.

While it'd probably worked in blender the correct way the addon expects is to parent the mesh to the armature and weight-paint it to the new bone. For your case simply adding all of the mesh vertices to the new bone vertex group should work fine.

**Comment by mrStafflink** [comment]
It's just that the mesh is attached to several bones, (2 pieces of them) and I just shift+P created a copy of it, and then attached it with ctr + P selected the bone and the desired mesh and everything worked..... all 2 original and new bones interacted with the mash gun, and everything worked smoothly, as soon as I made an export, it broke everything in blender and in OE.....

**Comment by mrStafflink** [comment]
Can this be fixed??? Or am I doing something wrong, sorry for my English as it is not my native language and I am writing with the help of a translator(

**Comment by amorgun** [comment]
There are different ways for rigging and the addon currently doesn't support what you are trying to do.
Here is the relevant video: https://youtu.be/DDeB4tDVCGY?si=TaPKgguCOBUSJdTV
Right now the addon supports the first way with bone weight and you are trying to use the second one.
I'll see how to implement it as well but for now I recommend using the intended way.

**Comment by mrStafflink** [comment]
Ok, thanks for the tip, I'll try to study the video!

**Comment by amorgun** [comment]
Окей, думаю можно перестать страдать с переводчиком.
Я сделал новый релиз, теперь там можно привязывать меш к кости, как ты изначально пытался: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha10
Вообще странно, что в варианте с арматурой понадобилась привязка к трем костям, хотя изначально вроде бы работала привязка к одной кости.

**Comment by mrStafflink** [comment]
Only works, if you take and bind with the help of automatic detection of weights. But when all bones are bound to the mesh and you have to delete unnecessary groups in the vertex group and leave the necessary ones, and then for each group, paint the mesh completely in red color)) only in this way when exporting, the binding to the mesh and to a new bone is preserved.

**Comment by mrStafflink** [comment]
No does not help, yes exports for some reason weights break, namely from red blender makes green weights.... 

The first photo is before export. 
![Скриншот 27-11-2024 202201](https://github.com/user-attachments/assets/de9f3185-bc20-4b6e-9347-aba15212cf28)

Second photo after exporting.... 
![Скриншот 27-11-2024 202113](https://github.com/user-attachments/assets/d150a3d2-396d-41bb-bc9b-e943c901a4a9)

**Comment by mrStafflink** [comment]
Becomes pale green, and all vertex groups in this mesh model....

**Comment by amorgun** [comment]
Расскажи, что ты пытаешься сделать. Пока выглядит очень странно, у болтера нужна только одна кость, непонятно зачем ещё две надо.

**Comment by mrStafflink** [comment]
I figured it out, to attach 3 bones you just need to make an accordion, like the first bone is attached to the second, the second bone is attached to the third, the third bone to the base of the main bone in the model..... I want to make a machine gun synchronization animation that the bones do not interfere with each other. You can look at the turret of the space troopers, there are a lot of bones, and animations work together. In one meshes (and colored) used 2-3 bones, and they do not interfere with each other, in the animation.

**Comment by mrStafflink** [comment]
![Скриншот 27-11-2024 212957](https://github.com/user-attachments/assets/79b50092-378c-4321-b440-5815c49fff6c)
here are 3 bones in one mesh, and they're connected by an accordion.

**Comment by mrStafflink** [comment]
And then all 3 bones work, the only thing left to do is to set everything up correctly in the animation so that there are no conflicts in the bones.

**Comment by amorgun** [comment]
It looks like this problem is solved so I'm closing this issue.
