### ISSUE TITLE
Blender for some reason breaks animations that I haven't touched! 

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#11]
Hello! Blender, breaks animations that I haven't touched or edited. For example, I made a new animation of the terminator vertical/horizontal pointing when running and simple shooting. The strangest thing is that I made an export and everything was fine, but when I made an import to create its new animation, then all animations idle, melee, shooting, etc., broke..... very strange, because when I first made an export, everything was fine, but after importing, everything stopped working, except for the animation of pointing. 

Also if you just view the animations in blender, then over time also begin to appear some bugs, and it's strange how it will work when exporting and it's hard to understand whether it's the animation itself is such, or blender just does not show so, and all is well.

![Скриншот 28-11-2024 205900](https://github.com/user-attachments/assets/a330326a-02b8-4c61-bb92-58ab48bfb68a)
![Скриншот 28-11-2024 210135](https://github.com/user-attachments/assets/12b32583-450f-4eeb-b7a0-5f424ade848b)
![Скриншот 28-11-2024 210155](https://github.com/user-attachments/assets/d930180b-d2ea-46c2-a55b-f7319fe7a187)

**Comment by mrStafflink** [comment]
![Скриншот 28-11-2024 210923](https://github.com/user-attachments/assets/428fc3ea-bd59-49c6-8d1b-19ef0b94c0e0)

**Comment by mrStafflink** [comment]
It's scary to edit, the terminator has crooked weapon pointing animations and I already have experience in creating normal and good animation of vertical and horizontal pointing, using only u bone, when as in the original unit can use a bunch of torso and arm bones, which leads to bugs, in the form of dislocated arms or 1 sec the arm rises 90% up and it's not beautiful looks. In the units from soulstorm animations these are made correctly and logically than the original units (orcs, eldar, space marine, chaos)

**Comment by amorgun** [comment]
Can you explain the steps that led to the broken animations? Maybe you can give the .blend file that is broken after export?

**Comment by mrStafflink** [comment]
Well, I opened the terminator and created him 3 new animations, then made an export and opened in ee, there was everything ok, there were a little bit of inaccuracies, I opened this model again in blender and corrected a little bit of my animations and then again made an export, and then everything broke, and my animations are not broken, but those that did not touch broken....

**Comment by mrStafflink** [comment]
If after the first export you don't close blender and just continue working and export again, everything is ok.... If you close the unit in blender and then open it with import, the animations are broken, except for my created animations.

**Comment by mrStafflink** [comment]
And blender begins to display animations strangely, if you just view them, it becomes scary, because it is not clear whether the animation is broken or not.... 

![Скриншот 28-11-2024 215911](https://github.com/user-attachments/assets/9ddc3625-c8f4-45e9-a07a-6c05a6c4d8c9)

And after exporting everything is ok, it turns out blender sees strangely so does not accurately display, and is not informative. 

![Скриншот 28-11-2024 220007](https://github.com/user-attachments/assets/ac877993-5dee-4c4b-a7aa-6507f6ca6107)

**Comment by amorgun** [comment]
Can you attach here a .blend file with a new animation that does not export correctly?
The animation preview may look weird because some bones are rotated from the previous animation. Click "Pose -> Clear transform -> All" and check the action preview again.

**Comment by mrStafflink** [comment]
Here! here ebp, sbp, whe, whm after export. It's okay here! Take whm do an import into blender and immediately do an export and the animations are broken... maybe some bone in the animation needs to be touched. I also pass the blend file, it should be ok too.  
[terminator whm whe epb sbp blend.zip](https://github.com/user-attachments/files/17951717/terminator.whm.whe.epb.sbp.blend.zip)

**Comment by mrStafflink** [comment]
This is where it's broken! 
[bug terminator1 ebp sbp whm whe blend.zip](https://github.com/user-attachments/files/17951761/bug.terminator1.ebp.sbp.whm.whe.blend.zip)
I put a one in the name to make it easy for you to check them!

**Comment by amorgun** [comment]
Great find, thank you. I'll need some time to fix it.

**Comment by mrStafflink** [comment]
I realized this bug happens when I create a new animation and edit a new bone ... koda 1 time you do, then all ok and fine, but when you want to edit again (that is, to do again import, customize and then export) then at this point, breaks. Before, I only worked with meshes and markers and could do import/export a bunch of times, no problem. At least, there was no such bug....

**Comment by mrStafflink** [comment]
It's strange that the tank Leman russ orcs did not break, in terms of animation .... I opened it a bunch of times and changed the bones and meshes + created separate animations at the side machine guns.

**Comment by amorgun** [comment]
I hope it's fixed in the new release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha11
This bug occurred only on some specific models so a lot more testing on different models is required.

**Comment by mrStafflink** [comment]
Well, I edited the tanks and turned some listening posts, and changed in them animations of the rotation, because the buildings were turned to us back, and they should be turned to our face and because of this horizontal guidance did not work correctly, but I found a solution, it was necessary to change the guidance, and in corsix change one parameter (muzzle and origins in the unit ebps) Buildings and tank orcs did not break with multiple imports and exports, but the units of infantry, broken. . it turns out so far)))

**Comment by mrStafflink** [comment]
Did the broken unit start working normally after your fix? Terminator, space marine, scout?

**Comment by mrStafflink** [comment]
that I sent you in the zip archives?

**Comment by amorgun** [comment]
> Did the broken unit start working normally after your fix? Terminator, space marine, scout?

Yes, the terminator is exported correctly now.

**Comment by mrStafflink** [comment]
Awesome, we are on the cusp of a new branch in modding development in dawn of war!!!!
