### ISSUE TITLE
Exports and imports break the banner of factions! 

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#12]
For some reason, when exporting the rear part of the texture, it becomes...

This is from the front
![Скриншот 29-11-2024 013851](https://github.com/user-attachments/assets/7e873026-ca29-4b6b-afb5-d53efa5e2ef5)

And this is the back of the banner.  
![Скриншот 29-11-2024 013837](https://github.com/user-attachments/assets/db3001ea-a481-4c0b-af9b-09e385340789)

**Comment by mrStafflink** [comment]
Nope, also on import.... I haven't opened this model yet. 
![Скриншот 29-11-2024 014340](https://github.com/user-attachments/assets/4cf948f3-2a4a-422e-9945-84150cabd972)

**Comment by amorgun** [comment]
For me the scout imports all right. Can you send me the .blend file with the broken banner?

**Comment by mrStafflink** [comment]
open sergeant, or marina.

**Comment by amorgun** [comment]
They also look correct

**Comment by mrStafflink** [comment]
I'll be right there.

**Comment by mrStafflink** [comment]
[space_marine whm blend.zip](https://github.com/user-attachments/files/17952819/space_marine.whm.blend.zip)

**Comment by mrStafflink** [comment]
It's better in-game to watch it when he puts the banner on the point. You can see the textures on one side, and only a few pieces on the other....

**Comment by mrStafflink** [comment]
I basically know how to fix it, duplicate the texture and change the face orientation.... on the copy. ehhhhh extra work, now I have to check my units for this bug!(((

**Comment by amorgun** [comment]
For some reason your file has Backface Culling enabled while for me it's disabled after the import. If you disable it the banner looks fine.
I guess I'll explicitly disable it after import.

**Comment by mrStafflink** [comment]
can you tell me where this parameter is?

**Comment by amorgun** [comment]
[Screencast from 29.11.2024 02_49_58.webm](https://github.com/user-attachments/assets/88a00a9d-4a8f-4c3a-b4dc-96da20ee35e2)

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/cbbd64ca-ee0d-4a6c-8f6c-963c38de02e9)

**Comment by mrStafflink** [comment]
didn't help, only one side is visible and the other only a piece of the flag....

**Comment by mrStafflink** [comment]
I have it disabled by default.

![Скриншот 29-11-2024 030905](https://github.com/user-attachments/assets/c6b5c4ea-de69-431a-8817-1967d7ffa9df)

**Comment by amorgun** [comment]
Test if removing the Wield modifier from the banner helps with export.

[Screencast from 29.11.2024 13_34_37.webm](https://github.com/user-attachments/assets/a853a881-6bbb-43a2-a2ff-e22cfcf68b00)

**Comment by mrStafflink** [comment]
No it doesn't help, I think it was necessary to disable this function in meshes (welt) even before exporting, just the model is already broken and half of animations broke after another import and export..... but it shows the banner clipping in oeu.  

![Скриншот 29-11-2024 030905](https://github.com/user-attachments/assets/55d37d0f-3d30-4571-865c-c4b11143c366)
![Скриншот 29-11-2024 200839](https://github.com/user-attachments/assets/abd206a2-b871-4774-900a-74b8f11bd680)
![Скриншот 29-11-2024 200918](https://github.com/user-attachments/assets/4cad70b6-908b-4ac6-be3c-899477888316)
![Скриншот 29-11-2024 200948](https://github.com/user-attachments/assets/5af6e3ac-322a-4720-b25e-c7ce4700ae34)
![Скриншот 29-11-2024 201019](https://github.com/user-attachments/assets/1548e0b0-579a-4b3c-802d-30005c5e6c63)

**Comment by mrStafflink** [comment]
Here's this model, half of the unit's animation broke after export.... 
[Uploading space_marine1 blend whm sbp whe ebp .zip…]()

**Comment by mrStafflink** [comment]
Получилось, но только с дефолтной моделью, вытащенной из мод студию корсикс... Возможно более ранее версия аддона, ломало это. Я удалил weld и стало ок, и не трогал Backface culling.

![image](https://github.com/user-attachments/assets/35314dcb-d57f-43be-8624-1371142e0c12)

**Comment by amorgun** [comment]
I removed default Weld modifier in the new release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha11

**Comment by amorgun** [comment]
For the already exported models I can't help much because the modifier already removed some of the banner vertices during the export. You need to reexport the models without the modifier to bring the vertices back.

**Comment by mrStafflink** [comment]
No big deal, I'll just duplicate the banner and turn it around and it will be all beautiful, apply face orientation!

**Comment by mrStafflink** [comment]
Keep up the good work and further develop your project for blender) already some people in my neighborhood are starting to get interested in your plugin and are thinking of switching to blender!
