### ISSUE TITLE
When importing the main destroyer, it writes about errors in the model markers.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#13]
Hello! I decided to open the Eldar Heavy Destroyer and it gave me this. He doesn't like something about the markers..... maybe it's not a problem, but I thought I'd tell you about it. 

The model is original and I just imported it into blender.

![Скриншот 01-12-2024 112417](https://github.com/user-attachments/assets/0f01e931-2e7f-4522-82ea-5da0a6463ec5)

![Скриншот 01-12-2024 113007](https://github.com/user-attachments/assets/39af5c11-cb48-473b-a230-8769bc8b35e3)

**Comment by amorgun** [comment]
My best guess is that the original model authors incorrectly exported markers or edited them with a hex editor because there are no bones with the given names in the file.

**Comment by mrStafflink** [comment]
I looked in the oe and found no no problems in the fx. So these markers, ballast and not necessary yes?

**Comment by amorgun** [comment]
Without the correct parent their fx is probably played underground. If the game doesn't actually use them you can delete them.

**Comment by mrStafflink** [comment]
Yeah I didn't notice their use! Thanks for the clarification ! I haven't seen any more bugs with animation breakage in units. I checked it through the object editor before replacing my whm with blender's export whm.

**Comment by mrStafflink** [comment]
These markers are not used, mandrake also has them.... I think they were transferred from another unit and not added to the bones and not prescribed.... they're garbage...... 
We can basically close this discussion.

**Comment by mrStafflink** [comment]
how many times can you apply this parameter on old models that were exported in an older version of the addon? Vertex merging position threshold = 0.01. And what is the best thing to use for the default?  Vertex merging position threshold = 0 and Vertex merging normal threshold = 0.01?????

**Comment by amorgun** [comment]
There is no sense in applying it more than once but it wouldn't break much either.  
`position threshold` is basically the same as the threshold in the Weld modifier.
Zero is useful when you are editing an existing DoW model because it's more likely to export exactly the same model.
Values higher than zeros result in merging vertices that are close together. It's useful when exporting models not from DoW or optimizing existing models. Higher values result in more aggressive merging but have a higher chance of breaking models.
`normal threshold=0.01` looks like a good default and should work well most of the time.

**Comment by mrStafflink** [comment]
Vertex merging position threshold = 0 and Vertex merging normal threshold = 0.01

It's best to keep it that way, right? I noticed that the exported models do not load as the original system, namely I through ffe add 1024 by 1024 textures on the weapons of units, with a large number of troops, there was a ripple and twitching camera, HERE it is not! I am happy! Is it export still optimizes or just fixes what was prescribed through ffe?

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/a8c1877f-d9f2-4657-9f35-c03a5383aa20)

I have a whole bunch here and no camera lags or ripples) although the weapons in their hands are hd (each gun is 256 by 256 pixels)

**Comment by amorgun** [comment]
> Vertex merging position threshold = 0 and Vertex merging normal threshold = 0.01
Sure it will work.

I'm not sure what you've changed with FFE. If you simply replaced links to .rsh files the addon shouldn't change it. If you used textures exported by the addon it resized textures to 768 by default so it could matter.

**Comment by mrStafflink** [comment]
No textures are not extracted with your addon, they are 1024 by 1024, but micro freezes now no. If you write them through ffe (path and in msgr) write exactly these textures, then lags and micro freezes reappear, but if you do import, and then export without specifying texture changes, that is, leave the original, then lags and micro freezes disappear. I also checked through photoshop and they did not reduce to 768 resolution. I think the plugin optimizes or just does everything better that ffe.
