### ISSUE TITLE
Blender export breaks the dark eldar destroyer.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#14]
I made an export of sgm model to the object editor and noticed that some of the meshes are not on the model of the destroyer.... Of course it's the oe, but if I start doing anything with the meshes of the model. In general, it looks like the model is broken when exporting) 

![image](https://github.com/user-attachments/assets/a72ce749-6b49-460b-9f8f-6d69bc7c8f32)

**Comment by amorgun** [comment]
As far as I understand it's just an OE problem and the exported .whm model works fine in the game.

**Comment by mrStafflink** [comment]
All right! I'll check back later and report back!

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/84759a62-e041-4519-90e0-fac21e55438b)

**Comment by mrStafflink** [comment]
After exporting whm broke.... I used the original and didn't touch anything in the model except import and export.

**Comment by mrStafflink** [comment]
The Overlord has lost his body.)

**Comment by amorgun** [comment]
It looks like after removing the Weld modifier in #12 there are too many vertices and the game can't display it now.

**Comment by mrStafflink** [comment]
Unfortunate... sad.

**Comment by mrStafflink** [comment]
maybe bring it back, just remove it from the banners, huh?

**Comment by amorgun** [comment]
I'll see what I can do

**Comment by amorgun** [comment]
I've improved the algorithm of vertex merging in this release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha12
Now the vertex count increases by 5% after the first export. It's still not perfect but it's much better than the 300% growth before.
I checked that it doesn't break banners again but more testing would be nice.

**Comment by mrStafflink** [comment]
And previously merged at 300%, can it affect performance a? Like the model becomes larger or it's not dangerous?

**Comment by amorgun** [comment]
Yes, it's not great. I recommend reexporting old models with `Vertex merging position threshold > 0` (e.g. 0.01) to merge duplicated vertices.
