### ISSUE TITLE
Lord destroyer, loses body when exporting from blender...

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#15]
Greetings, the lord destroyer of dark eldar, is still losing his whole body, I installed the latest addon version and pulled the original whm from the game, but still the lord is losing mes... 

I'll try checking animations and render meshes in animations, maybe the problem is exactly what is breaking animations and their mapping in animations.

![image](https://github.com/user-attachments/assets/71dcd2cf-0e36-4360-bf39-43414477067a)

Guardsman to the right of the lord, loses his body too)) 

![image](https://github.com/user-attachments/assets/5860ba71-2687-4fb1-abd1-13afc4f23476)

**Comment by mrStafflink** [comment]
Well, this is the original.

**Comment by mrStafflink** [comment]
2.2 megabytes

**Comment by mrStafflink** [comment]
After exporting, it becomes 2.6 мб

**Comment by amorgun** [comment]
So it's missing even when you use the original .whm? What has changed then?

**Comment by mrStafflink** [comment]
The lord is there when I use the original, there is none after exporting...

**Comment by mrStafflink** [comment]
I took out the original and it works, after exporting him and his right bodyguard, disappearing bodies)))

**Comment by amorgun** [comment]
Just to be sure can you attach here the exported .whm that doesn't work?

**Comment by mrStafflink** [comment]
[dais of destruction1.zip](https://github.com/user-attachments/files/17981999/dais.of.destruction1.zip)
Here is the original whm and whm1 and sgm1 export of the original.

**Comment by amorgun** [comment]
It works fine for me so I have to rely on your help for testing.
Here is a new release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha13
It should produce almost exactly the same model as it was before.
Try exporting with `Vertex merging position threshold = 0` as well as `Vertex merging position threshold = 0.01` and check if any of this works.

**Comment by mrStafflink** [comment]
Okay, I'll try to check it out!

**Comment by mrStafflink** [comment]
Now export doesn't work at all no sgm no whm( writes this! I wrote different 0.01 digits in Vertex merging position threshold and Vertex merging position threshold.

![Скриншот 04-12-2024 234324](https://github.com/user-attachments/assets/10503091-38d2-4071-bf2c-28c568e0f599)

**Comment by mrStafflink** [comment]
Even Mandrake is not exported in any way)

**Comment by amorgun** [comment]
That's odd. Try restarting blender.

**Comment by mrStafflink** [comment]
I got it! Lord and his right guardsman do not lose their bodies, but there is still a bug.... it's a pity of course, just before moving a modified whm into the game, I look at how it works in the object editor....

![Скриншот 05-12-2024 000728](https://github.com/user-attachments/assets/84c8322f-80cb-4d06-89d8-d4228fff9d35)
![Скриншот 05-12-2024 000758](https://github.com/user-attachments/assets/aa90e162-0843-4ae2-a2b0-343b7b581405)

I used this one, i.e. the original of your customizations!
Vertex merging position threshold = 0 and Vertex merging position threshold = 0.01

**Comment by mrStafflink** [comment]
![Скриншот 05-12-2024 001648](https://github.com/user-attachments/assets/d6b544bc-c8dc-4f8c-9fec-75956667b3a3)
These are the ones I used

**Comment by mrStafflink** [comment]
Well, I mean that in the editor of objects, the lord still loses the body and the guard. It's not critical, I just used to consider the oe 100% true, like what you saw in it, and in the game, but from the fact that in the game lord ok and in the oe is not, that's what I'm afraid, suddenly and visual bug, namely a bug model....

**Comment by mrStafflink** [comment]
In the game itself it's ok, in the object editor it's not.

**Comment by amorgun** [comment]
To my understanding there is a budget for vertices and vertices over it are not displayed. It looks like this limit is different between OE and the actual game.
But it's hard to test because unlike .whm there are not many reference .sgm files for looking into its format.

**Comment by mrStafflink** [comment]
Basically on the lord we can close the discussion.... or leave a record somewhere, so that others know that the lord is not fully displayed in the oe))))
