### ISSUE TITLE
Increased animation speed, after exporting!

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#16]
Good evening! After exporting Dark Eldar to Mandrake, his melee attack speed increases, almost 50%, other animations are not broken.

That said, I just did an export of sgm and whm to the object editor, for editing special effects and missing them in some animations. 

Funny error, in fact you can easily fix it by creating a separate model and there slow down the animations by 50%, and then through the file format editor to throw the modified animations in the original whe Mandrake (this is a theory, while I have not done so) 

In the archive is the original whm and whm1, sgm1, blend export from blender (there I didn't touch anything just import and export)
[Mandrake whm whm1 sgm1 blend.zip](https://github.com/user-attachments/files/18013946/Mandrake.whm.whm1.sgm1.blend.zip)

**Comment by amorgun** [comment]
Congratulations, you've found a rare animation with 15 fps. I've re-uploaded the release with this issue fixed: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha13

**Comment by mrStafflink** [comment]
Very prompt! I'm surprised. Hope the other units don't break ) I guess I have to watch the animation playback of the unit very carefully) xD
