### ISSUE TITLE
When exporting, the shadows of buildings on high settings are missing.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#18]
Hello, When exporting a building, it stops having shadows that are called shadow volume (stencil shadow volume) working. Of course, I do not use these shadows in the game, as many buildings have breaks of these shadows at a certain lighting map.....

That's before the building was exported. 
![image](https://github.com/user-attachments/assets/cbdb434b-2260-4ccd-83b6-f6addb1ffb64)

This is after exporting from the blender.
![image](https://github.com/user-attachments/assets/ab340643-98e1-41fe-aba8-a0477d6bbe4b)

Amorgon, you can take any building and see a bug like this.... is there any way to get those shadows back?

**Comment by mrStafflink** [comment]
This may be due to changes in the mesh model of the building.

**Comment by amorgun** [comment]
This data currently is not parsed from .whm nor it's exported. I had no information on how it's used or how you could previously edit it. I'll see if I can decode it.

**Comment by mrStafflink** [comment]
You might as well not worry about it, people mostly play on medium shadow map settings. Just for the sake of interest I turned on max shadows and saw this. In the original, these shadows, do not work well and many of these shadows, stretch or break at the contiguous angle of the light source in the game.

**Comment by amorgun** [comment]
Try this release: https://github.com/amorgun/blender_dow/releases/tag/v0.15alpha3
Now you can import and export shadow volumes. There is also a button "Create shadow" on the DoW tools panel to quickly create shadow volumes for new meshes.
![20241226233922_1](https://github.com/user-attachments/assets/c442edae-2d8e-4412-8675-2bfce09434b4)

**Comment by mrStafflink** [comment]
Amorgun, I didn't understand where this parameter is, what is responsible for creating shadows.

**Comment by mrStafflink** [comment]
I can't find the dow toolbox in blender) where is it? Does it have to be turned on or am I confused.... I just haven't logged into blender in a couple weeks.

**Comment by amorgun** [comment]
It's in the sidebar
![Screencast from 28.12.2024 21_40_56.webm](https://github.com/user-attachments/assets/d4e330f7-d560-43d9-908b-fbf1e8177aaa)

**Comment by mrStafflink** [comment]
THANK YOU VERY MUCH!
I'll check the shadows in the game.

**Comment by mrStafflink** [comment]
I have generated shadows at the orc chapters, but they do not appear in the game, while the folder shadows in blendere appeared and there are these shadows.....

**Comment by mrStafflink** [comment]
Amorgun, can you tell me more? Is it possible to check these shadows in blender, exactly how they work and if there are errors in them, exactly closed geometry, so that they at a certain angle of light on the map do not stretch to the entire screen a?

**Comment by amorgun** [comment]
The game uses an optional separate mesh for each object to cast shadows. Now blender imports these meshes so you can find them in the "Shadows" collection. Each mesh has a reference to its corresponding shadow mesh so you may edit it separately. 
It looks like only meshes that are force_skinned (i.e. fully attached to one single bone) can have shadows.
There is the "Create shadow" button in the DoW tools panel so you can simply select all meshes and click it to create new shadow meshes when possible.

**Comment by amorgun** [comment]
For the possible display errors I haven't tested all of the corner cases and just checked it works in the game.

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/48020378-bed5-4547-b4e2-5609886d680b)
I would like to fix this in the shadows.... this error occurs from the position of the light source, on other maps, there is no such problem, but there are on several. One person wrote that this is because of not closed geometry of the building share.

**Comment by amorgun** [comment]
I don't seem to be able to reproduce this issue. Can you give me steps to do so?
It looks like a map decoration shadow from the trees behind the building. If you think the problem is with the shadow mesh you can add remesh + decimate modifiers to guarantee it's a closed geometry.

**Comment by mrStafflink** [comment]
This is a 3x3 player mortalis map 
It's the original building and so is the map. It's called Mortalis.

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/06251f74-1b35-408c-b230-fa12f42c9020)

**Comment by amorgun** [comment]
Something seems to be wrong with landing_pad_shadow
I don't understand exactly what is wrong but you can fix this issue by removing the shadow from the landing_pad mesh or deleting the supports from the shadow.
![Screenshot from 2024-12-29 00-26-37](https://github.com/user-attachments/assets/317a5611-644f-481f-8de8-057d7ecb3b53)

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/25b6a2c4-ba02-44a4-a5fc-9217ad4e47dd)
Something to do with it, you can see a bright stripe.

**Comment by mrStafflink** [comment]
There's also the problem of the Valkyrie transport coming in.

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/184bcbe2-442a-42be-8463-b5541970c236)

**Comment by amorgun** [comment]
It seems the shadow system is a mess and this glitch occurs when some of the shadow volume faces align with the map light source at a particular angle. It's probably worth fixing the map setting instead of the model.

**Comment by mrStafflink** [comment]
Yes in principle, it is better not to play with such shadows.... turn them off and forget about them.)
