### ISSUE TITLE
The problem of exporting to whm from a blender.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#3]
Hello! When exporting a model, the lighting and shading on the equipment breaks down! Is this a plugin problem or is the blender using the ambient view parameters in the blender program itself when exporting? 
The funny thing is, if you export again, then the model will not break further... that is, the blender breaks the model once...

[bag!.zip](https://github.com/user-attachments/files/17637483/bag.zip)

**Comment by mrStafflink** [comment]
![1XxF-xzQ_EY](https://github.com/user-attachments/assets/945be80a-653f-493e-adb9-b55757f6419f)
![XaIchV4jnsk](https://github.com/user-attachments/assets/9d57a121-3db2-4769-93d1-5f54b4101a8d)

**Comment by mrStafflink** [comment]
This happens with all models... but animations and markers do not break the model, more precisely, I extract markers and coped animations through the file format editor, and they work! So your blender software is in big trouble!

If you want to make sure, just take any model and export sgm or whm, then open it in the game, or in a blender, and turn on the Viewport Shading mode in the blender, and you will see such a disaster....

**Comment by mrStafflink** [comment]
![Скриншот 06-11-2024 082321](https://github.com/user-attachments/assets/8a13f65a-30e6-44f8-aea9-3d75639de7ed)
this is before exporting the model.
![Скриншот 06-11-2024 082415](https://github.com/user-attachments/assets/5223a2f4-201c-4edc-8d26-316668274564)
this is after exporting the whm model.

**Comment by amorgun** [comment]
It looks like something is wrong with exporting vertex normals. I'll take a look at it.

**Comment by amorgun** [comment]
This should be fixed in the version 0.14alpha5: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha5
