### ISSUE TITLE
the export is constantly whm, as well as sgm uses the Shade Smooth parameter!

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#5]
Hello again, I think I understood why the export breaks the normal map and this is the Shade Smooth parameter! It is constantly turned on when exporting the model, and if Shade flot is on, then the export will still forcibly turn on the shade Smooth parameter. What should I do, maybe I'm exporting incorrectly or do I need to apply some parameters in the blender?

before export
![Скриншот 06-11-2024 215235](https://github.com/user-attachments/assets/40add056-b47a-473c-aa45-793d5f35909e)

after exporting the whm and sgm file
![Скриншот 06-11-2024 215248](https://github.com/user-attachments/assets/947431bc-a7be-4cc2-bb2b-c532074bb0a7)

**Comment by amorgun** [comment]
This should be fixed in the version 0.14alpha5: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha5
