### ISSUE TITLE
When exporting breaks the invisible part of the unit's body, namely all parts of the animation vis, become visible!

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#6]
Hello again, you've done a great job fixing the normals for parts of the mesha model, but now I've discovered another bug. For some reason when exporting a predator model, the rendering of body parts is broken, namely all his upgrades and weapons are always visible, in all animations! The strangest thing is that I didn't touch anything, I just imported it into blender and exported the model to ObjectEditor.  

Это в ObjectEditor так выглядит. 
![Скриншот 17-11-2024 225536](https://github.com/user-attachments/assets/1d05fce9-ecdb-4046-be9b-3bb44990d54b)

It's in the game. 
![Скриншот 17-11-2024 224721](https://github.com/user-attachments/assets/69e58261-5afa-4750-8905-c4f932df2885)

**Comment by mrStafflink** [comment]
Probably many units can break like this when exporting, even if the animations were not touched and everything remained original....

**Comment by mrStafflink** [comment]
This applies to whm exports as well as sgm. Both formats break animations, or rather their rendering in certain animations vis body parts and weapons.

**Comment by mrStafflink** [comment]
I found that buildings break animation vis too. At the cosmodest post, vis all addons to the building, at all building animations.

I have the vis_level_1 animation selected, and I see the animation of the rolled building... 
![image](https://github.com/user-attachments/assets/70397d8f-812e-430f-88ce-218d6fdeeaa2)

**Comment by mrStafflink** [comment]
I found that blender breaks/unchecks the force_invisible parameters, if you enable these ticks then everything becomes normal, but there are a lot of animations and it's just not convenient then to put these ticks, so you can make a mistake and finally break everything.....   

This is where I ticked the boxes.
![Скриншот 17-11-2024 233519](https://github.com/user-attachments/assets/b3b78e5a-d322-48f8-a37d-6c68b90c50f5)

Now I can't see the part of the model that I don't want to see. 
![image](https://github.com/user-attachments/assets/862a3867-2e4a-4f2c-b6b6-9e144ab37748)

**Comment by amorgun** [comment]
It should be fixed in this release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha7
