### ISSUE TITLE
The information content of the markers on the model is not clear.

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#8]
Hello again! Is it possible to change the design of markers in blender so that they would be similar to those in oe (ObjectEditor) or 3max? It's just hard to understand their location in space and it's not intuitive how they are set up and how they are rotated with respect to x,y,z.

The first picture is in the blender. 
![Скриншот 21-11-2024 214949](https://github.com/user-attachments/assets/a74d3c3c-b83c-4f10-9608-1da1e556aabe)

The second picture is in the OE.
![Скриншот 21-11-2024 214909](https://github.com/user-attachments/assets/0d984440-602c-41a5-8e6e-0f30dc1370e4)

It's hard to customize them and how to position them the way I need them. Can they be made more informative or a different design eh?

**Comment by amorgun** [comment]
The best I can do is this: 
![Screenshot from 2024-11-23 02-03-31](https://github.com/user-attachments/assets/3cc971de-af39-4500-bea8-4461e8a870cf)
I added the custom shape in this release: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha8
You can enable marker name display for the Armature in the "Data -> Viewport Display" tab. Also you can hide the "Skeleton" bone group to reduce visual clutter.

**Comment by mrStafflink** [comment]
You're the best! A big human THANK YOU! Now I will be able to make an infinite amount of markers on models!

**Comment by amorgun** [comment]
No problem. It would be nice if you add a star to the repo,

**Comment by mrStafflink** [comment]
Yes, there are no problems in exporting, and in oe, everything seems to be ok. It remains only to test my changes in the game itself. Thanks again for everything! Your labor, great!)

**Comment by mrStafflink** [comment]
![image](https://github.com/user-attachments/assets/cd7ed84c-c261-4f1f-a8c2-9cd72bd79e24)

**Comment by amorgun** [comment]
@mrStafflink I found a problem with marker orientation sometimes being different from OE so you may want to use the newer version: https://github.com/amorgun/blender_dow/releases/tag/v0.14alpha9

**Comment by mrStafflink** [comment]
I wonder if I'll try!
