### ISSUE TITLE
Export, relic point, strategic point and cool point, not working!  

### ISSUE THREAD

**Issue by mrStafflink** [amorgun/blender_dow#9]
Hello again! When exporting, for example: Relic point, blender writes an error! Also before importing it writes a warning that something is missing....   

The first photo, importing it into the blender. 
![Скриншот 22-11-2024 225850](https://github.com/user-attachments/assets/0adb1d43-c8f9-4cca-83e3-73b59093ec8d)

Second photo, exporting a point. 
![Скриншот 22-11-2024 225923](https://github.com/user-attachments/assets/4fc8ff9d-47c8-4d3b-b8bd-45beeefa5e69)

It's a shame that exporting/importing points, works like this, I just made a fix for the hatch opening animation in the relic point... In the original game, the hatch doesn't open, and I fixed that, but ran into this error. However, i extracted all the rsh and whm!

**Comment by mrStafflink** [comment]
That's the mistake left, it's not considered dangerous or wrong eh?

![Скриншот 23-11-2024 025933](https://github.com/user-attachments/assets/32576f7f-9f51-4a23-8917-02e0fa93d7c2)

**Comment by mrStafflink** [comment]
It occurs when importing a point into blender

**Comment by amorgun** [comment]
I guess the model is a bit weird but it doesn't affects import in any way.

**Comment by mrStafflink** [comment]
Yes, there are no problems in exporting, and in oe, everything seems to be ok. It remains only to test my changes in the game itself. Thanks again for everything! Your labor, great!)
